BoxLayout:
    orientation: "vertical"

    Label:
        id: resultado
        text: ""

    GridLayout:
        cols: 4
        
        Button:
            text: "7"
            on_press: resultado.text += self.text
        Button:
            text: "8"
            on_press: resultado.text += self.text
        Button:
            text: "9"
            on_press: resultado.text += self.text
        Button:
            text: "+"
            on_press: resultado.text += self.text

        Button:
            text: "4"
            on_press: resultado.text += self.text
        Button:
            text: "5"
            on_press: resultado.text += self.text
        Button:
            text: "6"
            on_press: resultado.text += self.text
        Button:
            text: "-"
            on_press: resultado.text += self.text

        Button:
            text: "1"
            on_press: resultado.text += self.text
        Button:
            text: "2"
            on_press: resultado.text += self.text
        Button:
            text: "3"
            on_press: resultado.text += self.text
        Button:
            text: "*"
            on_press: resultado.text += self.text

        Button:
            text: "0"
            on_press: resultado.text += self.text
        Button:
            text: "."
            on_press: resultado.text += self.text
        Button:
            text: "="
            on_press: app.calcular(resultado.text)
        Button:
            text: "/"
            on_press: resultado.text += self.text

        Button:
            text: "C"
            on_press: app.limpiar()
